### ISSUE TITLE
inconsistent/duplicitous font size frameworks?

### ISSUE THREAD

**Issue by caseyg** [opengovfoundation/opengovfoundation-theme#2]
can potentially reconcile these later, or just start fresh/regenerate from one of the font frameworks—not a huge deal, but it appears to me that there are several different frameworks (bootstrap, gridlover, rem, px) trying to exert font sizing rules sitewide and the result is pretty complicated and hard to adjust in relation to what the mockups lay out

**Comment by jathayde** [comment]
Choose whichever you want. I personally prefer the REM sizing SCSS helper I added, but you're the one who needs to make it work :) Benefit of REM is that it drops back to the initial base declaration (16px/100% font size) across the board, so you have less of the nesting issues where you change one font size and all the children sizes shrink as well.

**Comment by krusynth** [comment]
`rem`s break horribly with stock bootstrap, fwiw.  (Thus the boilerplate I through together, though that's probably got some bugs as well.)   

Whatever gets this done easiest/quickest takes precedence here - I'm ok if the rhythm isn't perfect as long as it breaks nicely for mobile.
